tasks:
  - before: .gp/before.sh
    init: .gp/init.sh
    command: yarn start

ports:
  - port: 1234
    onOpen: open-preview

vscode:
  extensions:
    - dubadub.Cooklang
    - elmTooling.elm-ls-vscode
