#!/bin/sh
set -eux

which pandoc || (apt-get update && apt-get install -y pandoc) || (sudo apt-get update && sudo apt-get install -y pandoc)
mkdir -p dist
cp ./src/main.css ./dist/

for src in `ls src/*.md`; do
    ./scripts/build-md "$src"
done