#!/bin/sh
set -eu
rm -rf ./dist
./scripts/dist

concurrently -k \
    "chokidar \"src/*.css\" -c \"cp {path} ./dist\" " \
    "chokidar \"src/*.md\" -c \"./scripts/build-md {path}\" " \
    "serve dist"